-- 코드를 입력하세요
SELECT T1.ANIMAL_ID, T1.ANIMAL_TYPE, T1.NAME
FROM
(SELECT *
FROM ANIMAL_INS AI
WHERE AI.SEX_UPON_INTAKE LIKE 'Intact%') T1
JOIN
(SELECT *
FROM ANIMAL_OUTS AO
WHERE AO.SEX_UPON_OUTCOME LIKE 'Spayed%' OR AO.SEX_UPON_OUTCOME LIKE 'Neutered%') T2
ON T1.ANIMAL_ID = T2.ANIMAL_ID