-- 코드를 입력하세요
SELECT T1.FLAVOR
FROM 
(SELECT FH.FLAVOR, FH.TOTAL_ORDER
FROM FIRST_HALF FH) T1
JOIN
(SELECT J.FLAVOR, SUM(J.TOTAL_ORDER) TOTAL_ORDER
FROM JULY J
GROUP BY J.FLAVOR) T2
 ON T1.FLAVOR = T2.FLAVOR
ORDER BY T1.TOTAL_ORDER + T2.TOTAL_ORDER DESC
LIMIT 3

