SELECT T3.MEMBER_NAME, T4.REVIEW_TEXT, T4.REVIEW_DATE
FROM (
SELECT DISTINCT MEMBER_ID, MEMBER_NAME
FROM MEMBER_PROFILE
) T3
JOIN
(SELECT T1.MEMBER_ID, T2.REVIEW_TEXT, DATE_FORMAT(T2.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM
(SELECT RR.MEMBER_ID
FROM REST_REVIEW RR
GROUP BY RR.MEMBER_ID
ORDER BY COUNT(RR.REVIEW_SCORE) DESC
LIMIT 1) T1
JOIN
(SELECT RR.MEMBER_ID, RR.REVIEW_TEXT, RR.REVIEW_DATE
FROM REST_REVIEW RR
) T2
ON T1.MEMBER_ID = T2.MEMBER_ID
) T4
WHERE T4.MEMBER_ID = T3.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT